In [1]:
import pandas as pd
import os
import xlrd

In [2]:
file_path = "../../raw_data/travel_departures.csv"

# read csv and 'cut' data rows, columns and footer to desired data
data = pd.read_csv(file_path, encoding = 'ISO-8859-1', header=7, index_col = 1, skipfooter=6)
data_df = pd.DataFrame(data)

#Note, the data has been 
#(a) Country of citizenship classification and codes are from the: 
#Standard Australian Classification of Countries (SACC), 2016 (cat. no. 1269.0)
#(b) To confidentialise, estimates have been rounded to the nearest 10. As a result, sums of the components may not add exactly to totals.
data.tail(10)

<ipython-input-2-dd31200fe66d>:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  data = pd.read_csv(file_path, encoding = 'ISO-8859-1', header=7, index_col = 1, skipfooter=6)

,SACC code(a),Sep-2016,Oct-2016,Nov-2016,Dec-2016,Jan-2017,Feb-2017,Mar-2017,Apr-2017,May-2017,...,Mar-2020,Apr-2020,May-2020,Jun-2020,Jul-2020,Aug-2020,Sep-2020,Oct-2020,Nov-2020,Unnamed: 53
Country of citizenship(a),,,,,,,,,,,,,,,,,,,,,
Seychelles,9223.0,30,30,30,70,90,30,30,40,30,...,20,0,0,0,10,10,0,0,0,NaN
Somalia,9224.0,10,10,10,20,10,10,10,10,10,...,10,0,0,0,0,0,0,0,10,NaN
South Africa,9225.0,"5,190","5,510","5,330","7,230","10,010","4,410","4,990","7,190","4,990",...,"4,320",330,180,390,130,170,140,230,230,NaN
Eswatini,9226.0,10,0,0,10,0,0,10,10,10,...,0,0,0,0,0,0,0,0,0,NaN
Tanzania,9227.0,70,60,70,150,80,50,60,80,50,...,60,0,0,0,10,10,10,10,10,NaN
Uganda,9228.0,80,70,70,150,70,30,50,60,60,...,30,0,0,0,0,10,0,10,10,NaN
Zambia,9231.0,110,80,110,160,110,100,110,80,100,...,50,0,0,10,10,10,20,10,20,NaN
Zimbabwe,9232.0,420,370,510,830,610,370,360,530,450,...,250,0,0,20,40,20,50,50,70,NaN
"S & E Afr, nec",9299.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
Inadequately Described,NaN,"1,340","4,440","1,750",650,240,470,"1,190","1,440",770,...,630,130,100,80,130,180,270,"1,050",100,NaN

In [3]:
# transpose data
data_df = data_df.T
data_df

Country of citizenship(a),Australia,Norfolk Island,Australian External Territories nec,New Zealand,New Caledonia,Papua New Guinea,Solomon Islands,Vanuatu,Guam,Kiribati,...,Seychelles,Somalia,South Africa,Eswatini,Tanzania,Uganda,Zambia,Zimbabwe,"S & E Afr, nec",Inadequately Described
SACC code(a),1101,1102,1199,1201,1301,1302,1303,1304,1401,1402,...,9223,9224,9225,9226,9227,9228,9231,9232,9299,NaN
Sep-2016,"866,140",0,0,"155,740",0,"3,590",520,260,0,70,...,30,10,"5,190",10,70,80,110,420,0,"1,340"
Oct-2016,"701,180",0,0,"186,450",0,"3,150",480,420,0,60,...,30,10,"5,510",0,60,70,80,370,0,"4,440"
Nov-2016,"655,800",0,0,"150,930",0,"3,590",610,340,0,110,...,30,10,"5,330",0,70,70,110,510,0,"1,750"
Dec-2016,"956,990",0,0,"179,880",0,"4,610",880,710,0,130,...,70,20,"7,230",10,150,150,160,830,0,650
Jan-2017,"732,790",0,0,"164,000",0,"4,740",610,640,0,50,...,90,10,"10,010",0,80,70,110,610,0,240
Feb-2017,"540,330",0,0,"122,510",0,"2,580",340,430,0,50,...,30,10,"4,410",0,50,30,100,370,0,470
Mar-2017,"665,680",0,0,"143,840",0,"3,070",470,340,0,90,...,30,10,"4,990",10,60,50,110,360,0,"1,190"
Apr-2017,"809,460",0,0,"163,170",0,"3,260",470,450,0,70,...,40,10,"7,190",10,80,60,80,530,0,"1,440"
May-2017,"737,500",0,0,"142,080",0,"2,720",490,640,0,110,...,30,10,"4,990",10,50,60,100,450,0,770
Jun-2017,"875,110",0,0,"144,270",0,"3,210",540,390,0,90,...,30,10,"4,260",0,50,60,100,360,0,950
Jul-2017,"843,030",0,0,"165,840",0,"3,640",530,340,0,90,...,40,20,"6,030",0,80,50,110,440,0,"3,910"
Aug-2017,"783,000",0,0,"153,420",0,"2,920",340,340,0,70,...,30,10,"4,390",0,40,70,100,400,0,"1,960"
Sep-2017,"931,340",0,0,"155,290",0,"3,790",450,460,0,80,...,20,10,"5,140",10,70,50,120,450,0,"2,880"
Oct-2017,"708,050",0,0,"186,630",0,"3,650",720,520,0,120,...,20,10,"5,890",10,60,100,110,460,0,"3,210"
Nov-2017,"695,780",0,0,"151,510",0,"3,700",590,550,0,230,...,30,10,"5,360",10,90,70,110,510,0,660
Dec-2017,"981,710",0,0,"178,230",0,"4,150",830,"1,090",0,110,...,70,20,"7,560",0,140,130,160,820,0,660
Jan-2018,"747,560",0,0,"164,330",0,"4,210",600,510,0,70,...,90,20,"10,610",10,80,70,130,720,0,350
Feb-2018,"551,210",0,0,"121,230",0,"2,470",350,350,0,60,...,30,20,"4,560",0,90,40,90,360,0,460
Mar-2018,"747,370",0,0,"148,990",0,"2,900",470,520,0,120,...,40,10,"5,900",10,80,60,90,440,0,700
Apr-2018,"801,130",0,0,"152,950",0,"3,010",600,640,0,120,...,100,10,"7,030",30,90,220,180,460,0,650
May-2018,"770,910",0,0,"141,120",0,"2,610",580,770,0,160,...,30,10,"5,170",0,50,50,80,320,0,750
Jun-2018,"913,330",0,0,"146,010",0,"3,170",600,510,0,150,...,50,10,"4,660",0,70,70,100,410,0,740
Jul-2018,"885,390",0,0,"167,110",0,"3,370",520,440,0,110,...,30,20,"6,220",10,90,110,120,480,0,"1,590"
Aug-2018,"826,310",0,0,"160,830",0,"2,740",430,400,0,90,...,30,20,"4,760",0,50,60,100,500,0,"1,660"
Sep-2018,"951,390",0,0,"160,260",0,"3,290",520,630,0,100,...,40,10,"5,810",0,90,100,140,560,0,"1,490"
Oct-2018,"758,530",0,0,"187,630",0,"2,900",660,570,0,170,...,20,20,"6,150",0,80,100,100,380,0,"2,700"
Nov-2018,"717,530",0,0,"155,390",0,"3,340",640,710,0,200,...,30,20,"5,660",0,90,150,150,520,0,"1,850"
Dec-2018,"1,039,260",0,0,"181,790",0,"4,490",910,"1,570",0,180,...,60,30,"8,430",10,100,130,200,960,0,690
Jan-2019,"780,980",0,0,"164,720",0,"4,090",680,740,0,200,...,90,20,"10,860",10,90,80,160,770,0,310
Feb-2019,"555,740",0,0,"124,410",0,"2,650",440,470,0,110,...,30,20,"4,930",0,60,40,60,400,0,370
Mar-2019,"690,820",0,0,"146,790",0,"2,820",450,630,0,110,...,30,20,"5,610",0,70,50,80,390,0,840
Apr-2019,"885,880",0,0,"164,150",0,"3,440",400,780,0,100,...,20,30,"7,100",10,60,70,70,580,0,950
May-2019,"798,700",0,0,"145,670",0,"2,910",520,870,0,170,...,40,10,"5,430",10,60,80,80,380,0,"1,020"
Jun-2019,"905,070",0,0,"147,940",0,"3,500",610,690,0,150,...,40,20,"4,840",10,90,70,110,420,0,820
Jul-2019,"890,000",0,0,"167,310",0,"3,800",610,600,0,140,...,30,20,"6,160",10,70,60,80,490,0,"3,060"
Aug-2019,"828,290",0,0,"162,410",0,"3,530",440,720,0,140,...,20,10,"4,930",0,50,40,90,480,0,"2,310"
Sep-2019,"973,600",0,0,"164,390",0,"3,860",590,830,0,180,...,30,20,"5,720",10,70,80,110,520,0,"2,470"
Oct-2019,"773,880",0,0,"190,850",0,"3,400",700,920,0,180,...,40,20,"6,230",0,60,80,120,490,0,"3,290"
Nov-2019,"734,570",0,0,"157,460",0,"3,490",730,"1,060",0,200,...,40,30,"5,910",10,110,90,120,560,0,"1,630"
Dec-2019,"1,056,000",0,0,"193,340",0,"4,240",850,"1,600",0,210,...,80,30,"8,610",10,130,140,180,900,0,500
Jan-2020,"807,880",0,0,"170,600",0,"4,020",530,650,0,170,...,80,30,"11,530",0,100,70,180,820,0,310
Feb-2020,"527,820",0,0,"126,690",0,"2,630",420,630,0,80,...,40,20,"5,040",0,40,40,80,450,0,590
Mar-2020,"247,510",0,0,"87,620",0,"1,740",290,390,0,60,...,20,10,"4,320",0,60,30,50,250,0,630
Apr-2020,"3,480",0,0,"1,860",0,10,0,0,0,0,...,0,0,330,0,0,0,0,0,0,130
May-2020,"5,050",0,0,"3,140",0,140,30,0,0,0,...,0,0,180,0,0,0,0,0,0,100
Jun-2020,"7,280",0,0,"3,620",0,220,20,100,0,0,...,0,0,390,0,0,0,10,20,0,80
Jul-2020,"12,310",0,0,"3,790",0,130,40,0,0,0,...,10,0,130,0,10,0,10,40,0,130
Aug-2020,"14,330",0,0,"4,130",0,120,0,0,0,0,...,10,0,170,0,10,10,10,20,0,180
Sep-2020,"11,740",0,0,"3,410",0,70,0,290,0,0,...,0,0,140,0,10,0,20,50,0,270
Oct-2020,"11,860",0,0,"3,330",0,130,30,160,0,10,...,0,0,230,0,10,10,10,50,0,"1,050"
Nov-2020,"10,950",0,0,"3,400",0,110,0,20,0,40,...,0,10,230,0,10,10,20,70,0,100
Unnamed: 53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# drop first row
data_df = data_df.drop(["SACC code(a)"])
data_df

Country of citizenship(a),Australia,Norfolk Island,Australian External Territories nec,New Zealand,New Caledonia,Papua New Guinea,Solomon Islands,Vanuatu,Guam,Kiribati,...,Seychelles,Somalia,South Africa,Eswatini,Tanzania,Uganda,Zambia,Zimbabwe,"S & E Afr, nec",Inadequately Described
Sep-2016,"866,140",0,0,"155,740",0,"3,590",520,260,0,70,...,30,10,"5,190",10,70,80,110,420,0,"1,340"
Oct-2016,"701,180",0,0,"186,450",0,"3,150",480,420,0,60,...,30,10,"5,510",0,60,70,80,370,0,"4,440"
Nov-2016,"655,800",0,0,"150,930",0,"3,590",610,340,0,110,...,30,10,"5,330",0,70,70,110,510,0,"1,750"
Dec-2016,"956,990",0,0,"179,880",0,"4,610",880,710,0,130,...,70,20,"7,230",10,150,150,160,830,0,650
Jan-2017,"732,790",0,0,"164,000",0,"4,740",610,640,0,50,...,90,10,"10,010",0,80,70,110,610,0,240
Feb-2017,"540,330",0,0,"122,510",0,"2,580",340,430,0,50,...,30,10,"4,410",0,50,30,100,370,0,470
Mar-2017,"665,680",0,0,"143,840",0,"3,070",470,340,0,90,...,30,10,"4,990",10,60,50,110,360,0,"1,190"
Apr-2017,"809,460",0,0,"163,170",0,"3,260",470,450,0,70,...,40,10,"7,190",10,80,60,80,530,0,"1,440"
May-2017,"737,500",0,0,"142,080",0,"2,720",490,640,0,110,...,30,10,"4,990",10,50,60,100,450,0,770
Jun-2017,"875,110",0,0,"144,270",0,"3,210",540,390,0,90,...,30,10,"4,260",0,50,60,100,360,0,950
Jul-2017,"843,030",0,0,"165,840",0,"3,640",530,340,0,90,...,40,20,"6,030",0,80,50,110,440,0,"3,910"
Aug-2017,"783,000",0,0,"153,420",0,"2,920",340,340,0,70,...,30,10,"4,390",0,40,70,100,400,0,"1,960"
Sep-2017,"931,340",0,0,"155,290",0,"3,790",450,460,0,80,...,20,10,"5,140",10,70,50,120,450,0,"2,880"
Oct-2017,"708,050",0,0,"186,630",0,"3,650",720,520,0,120,...,20,10,"5,890",10,60,100,110,460,0,"3,210"
Nov-2017,"695,780",0,0,"151,510",0,"3,700",590,550,0,230,...,30,10,"5,360",10,90,70,110,510,0,660
Dec-2017,"981,710",0,0,"178,230",0,"4,150",830,"1,090",0,110,...,70,20,"7,560",0,140,130,160,820,0,660
Jan-2018,"747,560",0,0,"164,330",0,"4,210",600,510,0,70,...,90,20,"10,610",10,80,70,130,720,0,350
Feb-2018,"551,210",0,0,"121,230",0,"2,470",350,350,0,60,...,30,20,"4,560",0,90,40,90,360,0,460
Mar-2018,"747,370",0,0,"148,990",0,"2,900",470,520,0,120,...,40,10,"5,900",10,80,60,90,440,0,700
Apr-2018,"801,130",0,0,"152,950",0,"3,010",600,640,0,120,...,100,10,"7,030",30,90,220,180,460,0,650
May-2018,"770,910",0,0,"141,120",0,"2,610",580,770,0,160,...,30,10,"5,170",0,50,50,80,320,0,750
Jun-2018,"913,330",0,0,"146,010",0,"3,170",600,510,0,150,...,50,10,"4,660",0,70,70,100,410,0,740
Jul-2018,"885,390",0,0,"167,110",0,"3,370",520,440,0,110,...,30,20,"6,220",10,90,110,120,480,0,"1,590"
Aug-2018,"826,310",0,0,"160,830",0,"2,740",430,400,0,90,...,30,20,"4,760",0,50,60,100,500,0,"1,660"
Sep-2018,"951,390",0,0,"160,260",0,"3,290",520,630,0,100,...,40,10,"5,810",0,90,100,140,560,0,"1,490"
Oct-2018,"758,530",0,0,"187,630",0,"2,900",660,570,0,170,...,20,20,"6,150",0,80,100,100,380,0,"2,700"
Nov-2018,"717,530",0,0,"155,390",0,"3,340",640,710,0,200,...,30,20,"5,660",0,90,150,150,520,0,"1,850"
Dec-2018,"1,039,260",0,0,"181,790",0,"4,490",910,"1,570",0,180,...,60,30,"8,430",10,100,130,200,960,0,690
Jan-2019,"780,980",0,0,"164,720",0,"4,090",680,740,0,200,...,90,20,"10,860",10,90,80,160,770,0,310
Feb-2019,"555,740",0,0,"124,410",0,"2,650",440,470,0,110,...,30,20,"4,930",0,60,40,60,400,0,370
Mar-2019,"690,820",0,0,"146,790",0,"2,820",450,630,0,110,...,30,20,"5,610",0,70,50,80,390,0,840
Apr-2019,"885,880",0,0,"164,150",0,"3,440",400,780,0,100,...,20,30,"7,100",10,60,70,70,580,0,950
May-2019,"798,700",0,0,"145,670",0,"2,910",520,870,0,170,...,40,10,"5,430",10,60,80,80,380,0,"1,020"
Jun-2019,"905,070",0,0,"147,940",0,"3,500",610,690,0,150,...,40,20,"4,840",10,90,70,110,420,0,820
Jul-2019,"890,000",0,0,"167,310",0,"3,800",610,600,0,140,...,30,20,"6,160",10,70,60,80,490,0,"3,060"
Aug-2019,"828,290",0,0,"162,410",0,"3,530",440,720,0,140,...,20,10,"4,930",0,50,40,90,480,0,"2,310"
Sep-2019,"973,600",0,0,"164,390",0,"3,860",590,830,0,180,...,30,20,"5,720",10,70,80,110,520,0,"2,470"
Oct-2019,"773,880",0,0,"190,850",0,"3,400",700,920,0,180,...,40,20,"6,230",0,60,80,120,490,0,"3,290"
Nov-2019,"734,570",0,0,"157,460",0,"3,490",730,"1,060",0,200,...,40,30,"5,910",10,110,90,120,560,0,"1,630"
Dec-2019,"1,056,000",0,0,"193,340",0,"4,240",850,"1,600",0,210,...,80,30,"8,610",10,130,140,180,900,0,500
Jan-2020,"807,880",0,0,"170,600",0,"4,020",530,650,0,170,...,80,30,"11,530",0,100,70,180,820,0,310
Feb-2020,"527,820",0,0,"126,690",0,"2,630",420,630,0,80,...,40,20,"5,040",0,40,40,80,450,0,590
Mar-2020,"247,510",0,0,"87,620",0,"1,740",290,390,0,60,...,20,10,"4,320",0,60,30,50,250,0,630
Apr-2020,"3,480",0,0,"1,860",0,10,0,0,0,0,...,0,0,330,0,0,0,0,0,0,130
May-2020,"5,050",0,0,"3,140",0,140,30,0,0,0,...,0,0,180,0,0,0,0,0,0,100
Jun-2020,"7,280",0,0,"3,620",0,220,20,100,0,0,...,0,0,390,0,0,0,10,20,0,80
Jul-2020,"12,310",0,0,"3,790",0,130,40,0,0,0,...,10,0,130,0,10,0,10,40,0,130
Aug-2020,"14,330",0,0,"4,130",0,120,0,0,0,0,...,10,0,170,0,10,10,10,20,0,180
Sep-2020,"11,740",0,0,"3,410",0,70,0,290,0,0,...,0,0,140,0,10,0,20,50,0,270
Oct-2020,"11,860",0,0,"3,330",0,130,30,160,0,10,...,0,0,230,0,10,10,10,50,0,"1,050"
Nov-2020,"10,950",0,0,"3,400",0,110,0,20,0,40,...,0,10,230,0,10,10,20,70,0,100
Unnamed: 53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# drop last row
data_df = data_df.iloc[:-1]
data_df

Country of citizenship(a),Australia,Norfolk Island,Australian External Territories nec,New Zealand,New Caledonia,Papua New Guinea,Solomon Islands,Vanuatu,Guam,Kiribati,...,Seychelles,Somalia,South Africa,Eswatini,Tanzania,Uganda,Zambia,Zimbabwe,"S & E Afr, nec",Inadequately Described
Sep-2016,"866,140",0,0,"155,740",0,"3,590",520,260,0,70,...,30,10,"5,190",10,70,80,110,420,0,"1,340"
Oct-2016,"701,180",0,0,"186,450",0,"3,150",480,420,0,60,...,30,10,"5,510",0,60,70,80,370,0,"4,440"
Nov-2016,"655,800",0,0,"150,930",0,"3,590",610,340,0,110,...,30,10,"5,330",0,70,70,110,510,0,"1,750"
Dec-2016,"956,990",0,0,"179,880",0,"4,610",880,710,0,130,...,70,20,"7,230",10,150,150,160,830,0,650
Jan-2017,"732,790",0,0,"164,000",0,"4,740",610,640,0,50,...,90,10,"10,010",0,80,70,110,610,0,240
Feb-2017,"540,330",0,0,"122,510",0,"2,580",340,430,0,50,...,30,10,"4,410",0,50,30,100,370,0,470
Mar-2017,"665,680",0,0,"143,840",0,"3,070",470,340,0,90,...,30,10,"4,990",10,60,50,110,360,0,"1,190"
Apr-2017,"809,460",0,0,"163,170",0,"3,260",470,450,0,70,...,40,10,"7,190",10,80,60,80,530,0,"1,440"
May-2017,"737,500",0,0,"142,080",0,"2,720",490,640,0,110,...,30,10,"4,990",10,50,60,100,450,0,770
Jun-2017,"875,110",0,0,"144,270",0,"3,210",540,390,0,90,...,30,10,"4,260",0,50,60,100,360,0,950
Jul-2017,"843,030",0,0,"165,840",0,"3,640",530,340,0,90,...,40,20,"6,030",0,80,50,110,440,0,"3,910"
Aug-2017,"783,000",0,0,"153,420",0,"2,920",340,340,0,70,...,30,10,"4,390",0,40,70,100,400,0,"1,960"
Sep-2017,"931,340",0,0,"155,290",0,"3,790",450,460,0,80,...,20,10,"5,140",10,70,50,120,450,0,"2,880"
Oct-2017,"708,050",0,0,"186,630",0,"3,650",720,520,0,120,...,20,10,"5,890",10,60,100,110,460,0,"3,210"
Nov-2017,"695,780",0,0,"151,510",0,"3,700",590,550,0,230,...,30,10,"5,360",10,90,70,110,510,0,660
Dec-2017,"981,710",0,0,"178,230",0,"4,150",830,"1,090",0,110,...,70,20,"7,560",0,140,130,160,820,0,660
Jan-2018,"747,560",0,0,"164,330",0,"4,210",600,510,0,70,...,90,20,"10,610",10,80,70,130,720,0,350
Feb-2018,"551,210",0,0,"121,230",0,"2,470",350,350,0,60,...,30,20,"4,560",0,90,40,90,360,0,460
Mar-2018,"747,370",0,0,"148,990",0,"2,900",470,520,0,120,...,40,10,"5,900",10,80,60,90,440,0,700
Apr-2018,"801,130",0,0,"152,950",0,"3,010",600,640,0,120,...,100,10,"7,030",30,90,220,180,460,0,650
May-2018,"770,910",0,0,"141,120",0,"2,610",580,770,0,160,...,30,10,"5,170",0,50,50,80,320,0,750
Jun-2018,"913,330",0,0,"146,010",0,"3,170",600,510,0,150,...,50,10,"4,660",0,70,70,100,410,0,740
Jul-2018,"885,390",0,0,"167,110",0,"3,370",520,440,0,110,...,30,20,"6,220",10,90,110,120,480,0,"1,590"
Aug-2018,"826,310",0,0,"160,830",0,"2,740",430,400,0,90,...,30,20,"4,760",0,50,60,100,500,0,"1,660"
Sep-2018,"951,390",0,0,"160,260",0,"3,290",520,630,0,100,...,40,10,"5,810",0,90,100,140,560,0,"1,490"
Oct-2018,"758,530",0,0,"187,630",0,"2,900",660,570,0,170,...,20,20,"6,150",0,80,100,100,380,0,"2,700"
Nov-2018,"717,530",0,0,"155,390",0,"3,340",640,710,0,200,...,30,20,"5,660",0,90,150,150,520,0,"1,850"
Dec-2018,"1,039,260",0,0,"181,790",0,"4,490",910,"1,570",0,180,...,60,30,"8,430",10,100,130,200,960,0,690
Jan-2019,"780,980",0,0,"164,720",0,"4,090",680,740,0,200,...,90,20,"10,860",10,90,80,160,770,0,310
Feb-2019,"555,740",0,0,"124,410",0,"2,650",440,470,0,110,...,30,20,"4,930",0,60,40,60,400,0,370
Mar-2019,"690,820",0,0,"146,790",0,"2,820",450,630,0,110,...,30,20,"5,610",0,70,50,80,390,0,840
Apr-2019,"885,880",0,0,"164,150",0,"3,440",400,780,0,100,...,20,30,"7,100",10,60,70,70,580,0,950
May-2019,"798,700",0,0,"145,670",0,"2,910",520,870,0,170,...,40,10,"5,430",10,60,80,80,380,0,"1,020"
Jun-2019,"905,070",0,0,"147,940",0,"3,500",610,690,0,150,...,40,20,"4,840",10,90,70,110,420,0,820
Jul-2019,"890,000",0,0,"167,310",0,"3,800",610,600,0,140,...,30,20,"6,160",10,70,60,80,490,0,"3,060"
Aug-2019,"828,290",0,0,"162,410",0,"3,530",440,720,0,140,...,20,10,"4,930",0,50,40,90,480,0,"2,310"
Sep-2019,"973,600",0,0,"164,390",0,"3,860",590,830,0,180,...,30,20,"5,720",10,70,80,110,520,0,"2,470"
Oct-2019,"773,880",0,0,"190,850",0,"3,400",700,920,0,180,...,40,20,"6,230",0,60,80,120,490,0,"3,290"
Nov-2019,"734,570",0,0,"157,460",0,"3,490",730,"1,060",0,200,...,40,30,"5,910",10,110,90,120,560,0,"1,630"
Dec-2019,"1,056,000",0,0,"193,340",0,"4,240",850,"1,600",0,210,...,80,30,"8,610",10,130,140,180,900,0,500
Jan-2020,"807,880",0,0,"170,600",0,"4,020",530,650,0,170,...,80,30,"11,530",0,100,70,180,820,0,310
Feb-2020,"527,820",0,0,"126,690",0,"2,630",420,630,0,80,...,40,20,"5,040",0,40,40,80,450,0,590
Mar-2020,"247,510",0,0,"87,620",0,"1,740",290,390,0,60,...,20,10,"4,320",0,60,30,50,250,0,630
Apr-2020,"3,480",0,0,"1,860",0,10,0,0,0,0,...,0,0,330,0,0,0,0,0,0,130
May-2020,"5,050",0,0,"3,140",0,140,30,0,0,0,...,0,0,180,0,0,0,0,0,0,100
Jun-2020,"7,280",0,0,"3,620",0,220,20,100,0,0,...,0,0,390,0,0,0,10,20,0,80
Jul-2020,"12,310",0,0,"3,790",0,130,40,0,0,0,...,10,0,130,0,10,0,10,40,0,130
Aug-2020,"14,330",0,0,"4,130",0,120,0,0,0,0,...,10,0,170,0,10,10,10,20,0,180
Sep-2020,"11,740",0,0,"3,410",0,70,0,290,0,0,...,0,0,140,0,10,0,20,50,0,270
Oct-2020,"11,860",0,0,"3,330",0,130,30,160,0,10,...,0,0,230,0,10,10,10,50,0,"1,050"
Nov-2020,"10,950",0,0,"3,400",0,110,0,20,0,40,...,0,10,230,0,10,10,20,70,0,100

In [6]:
# export data
data_df.to_csv("../output_data/tourism_dep_data.csv", index = False)

FileNotFoundError: [Errno 2] No such file or directory: '../output_data/tourism_dep_data.csv'